const c = {
  SET_VIEWER_IMAGE_ID: "SET_VIEWER_IMAGE_ID",
  SET_TOUR_ID: "SET_TOUR_ID",
  SET_INTERFACE_OBJECT: "SET_INTERFACE_OBJECT",
  SET_SECOND_INTERFACE_OBJECT: "SET_SECOND_INTERFACE_OBJECT",
  SET_TOUR_MODE: "SET_TOUR_MODE",
  SET_WIDGET_VIEW: "SET_WIDGET_VIEW",
  SET_VIEWER_STATE: "SET_VIEWER_STATE",
};

export default c;

export enum TOUR_MODES {
  PREVIEW = "PREVIEW",
  EDIT = "EDIT",
}
