export enum IMAGE_STATUSES {
  CREATED = "CREATED",
  UPLOADING = "UPLOADING",
  UPLOADED = "UPLOADED",
  PROCESSING = "PROCESSING",
  PROCESSED = "PROCESSED",
  FAILED = "FAILED",
  IMPROVED = "IMPROVED",
  NOT_IMPROVED = "NOT_IMPROVED",
}
